prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - secretName: tls-prometheus
        hosts:
          - prometheus.nemedpet.germanium.cz
    hosts:
      - prometheus.nemedpet.germanium.cz # --- PROMETHEUS DOMAIN ---
    paths:
      - /
    pathType: Prefix

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - secretName: tls-grafana
        hosts:
          - grafana.nemedpet.germanium.cz

    hosts:
      - grafana.nemedpet.germanium.cz # --- GRAFANA DOMAIN ---
    paths:
      - /
    pathType: Prefix

alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - secretName: tls-alertmanager
        hosts:
          - alertmanager.nemedpet.germanium.cz

    hosts:
      - alertmanager.nemedpet.germanium.cz # --- ALERTMANAGER DOMAIN ---
    paths:
      - /
    pathType: Prefix
